/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.learnprogramming;

public class LearnJava {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new LearnJava().getGreeting());
    }
}
